config/routes.rb
KwFesb::Application.routes.draw do

  resources :recipes, :only => [:show, :index]

  resources :redacaos do
    collection do
      get :redacao
      get :find_essay
    end
  end

  resources :enems

  resources(:subscribes){
    resources(:registrations, :only => [:new, :create, :show]){
      collection do
        post 'search_cep'
      end
    }
  }


  post '/tinymce_assets' => 'tinymce_assets#create'
  resources :awards, :only => [:index, :show]
  resources(:libraries, :only => [:index, :show]){
    collection do
      get 'virtual_library'
      get 'news_libraries'
      get 'tcc_nts'
      get 'sites_interessantes'
    end
    member do
      get 'news_library'
      get 'tcc_nt'
      get 'sites_interessantes_itens'
    end
  }
  resources(:pre_subscribes, :only => [:create, :show]){
    member do
      get 'class_new'
    end
  }
  resources :sheets, :only => [:new, :create, :show]
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :displays, :only => [:index, :show]
  resources :researches, :only => [:index, :show]
  resources :works, :only => [:new, :create, :show]
  resources :contacts
  resources (:transfers){
    collection do
      get :download
    end
  }
  resources :ex_alunos , :only => [:new, :create, :show]
  resources(:channel_students, :only => [:index, :show]){
    resources :displays, :only => [:index, :show]
  }
  resources :social_actions, :only => [:index, :show]
  resources :commissions, :only => [:index, :show]
  resources :class_names, :only => [:index, :show]
  resources(:class_categories, :only => [:index, :show]){
    collection do
      get 'innership_standard'
    end
  }
  resources :institutions, :only => [:index, :show]
  resources (:homes, :only => [:index]){
    collection do
      get :search
      get :virtual_tour
      get :fesb50anos
      get :sae
      get :teste
    end
  }
  resources :user_sessions
  resources :edicts
  resources :regiments
  resources :standings
  resources :president_galleries

  resources (:simulateds, :only => [:index]){
    collection do
      post 'confirmation'
    end
  }

  match 'fesb50anos' => "homes#fesb50anos"
  match 'sae' => "homes#sae"
  match 'confirmacao' => "simulateds#confirmation"
  match 'confirmesuapresenca' => "simulateds#index"

  resources (:exams){
    collection do
      get 'simulador'
      get 'informacoes'
      get 'inscricao'
      get 'update_prices'
      get 'update_dates'
      get 'login'
      get 'ticket'
      get 'find_cpf'
      post 'find_result'
      get 'my_email'
      post 'find_my_email'
    end
  }
  resources (:socioeconomics){
    collection do
      get 'update_cities'
    end
  }
  resources (:users){
    member do
      get 'payment'
      post 'payment'
    end

    collection do
      post 'search_cep'
      get 'update_second_option'
    end
  }

  root :to => 'homes#index'
  match 'tourvirtual' => "homes#virtual_tour"
  match 'register' => "users#new"
  match 'login' => 'user_sessions#new'
  match 'logout' => 'user_sessions#destroy'

  namespace(:admin){
    resources :recipes
    resources :enems
    resources :redacaos
    resources :librarie_tab_names
    resources :itinerant_exams
    resources :registrations
    resources :file_imports
    resources (:sheets){
      member do
        get 'export_csv'
      end
    }
    resources :pre_subscribes
    resources :cataloguing_data
    resources :highlights
    resources :schedules
    resources (:subscribes){
        member do
	        get 'paid'
	        get 'cpaid'
	        get 'adjusts_ticket_date'
	        #ajuste de informação do usuario
	        get 'edit_user_data'
	        put 'user_data_update'
	        #ajuste de informação do vestibular
	        get 'edit_subscribe_data'
	        put 'subscribe_data_update'
	        #ajuste de informação socieconomica
	        get 'edit_socieconomic_data'
	        put 'socieconomic_data_update'
	      end
	      collection do
          
          get 'simuladao'
          get 'confirmeds'
          get 'notconfirmeds'
	        get 'management_report'
	        get 'management_porta'
          get 'management_class_room'
	        get 'management_presenca'
	        get 'update_dates'
          get 'pne_subscribes'
          get 'socieconomic_report'
	        #pesquisa data em relação ao vestibular
	        get 'search_date'
	        get 'update_cities'
	      end

    }
    resources :cities
    resources :class_styles
    resources :cities
    resources :class_styles
    resources (:categories){
      resources (:items){
          resources :item_images
      }
    }
    resources :teachers
    resources (:class_names){
        member do
          get "adjusts_period"
          put "save_adjusts_period"
          post "save_adjusts_period"
        end
        collection do
          get "disable_all_subscribe"
          get "enable_all_subscribe"
        end
        resources :class_images
    }
    resources :class_categories
    resources (:warnings){
        resources :warning_images
    }
    resources :type_warnings
    resources :works
    resources :contacts
    resources :ex_alunos
    resources :departments

    resources :categories

    resources :item_images
    resources :items
    resources :categories
    resources (:items){
        resources :item_images
    }

    resources(:exams){
      member do
        get :report
        get :presence
        get :import_file
        get :launch_note
        put :processing_note
        get :show_note
        get :ajust_message
      end
      collection do
        put :print_selected
      end
      resources(:exam_dates){
        member do
          get :report
          get :presence
          get :not_paid
          get :launch_note
          put :processing_note
          get :show_note
        end
        collection do
          get :results
        end
      }


    }

    resources :socioeconomics

    resources (:awards){
       resources :award_galleries
    }
    resources :scientific_initiations
    resources :statics, :only => [:index]

    #INSERIDO O MÓDULO DE CONTROLE DE USUARIOS DO CMS
    resources :users

    root :to => 'statics#index'
  }

  match '/500' => 'errors#error_500'
  match '/404' => 'errors#error_404'

  #VESTIBULAR

  # match 'vestibular' => "exams#index"
  # match 'vestibular/inscricao' => "exams#inscricao"
  # match 'simuladao' => 'exams#redirect_simuladao'
  # match 'vestibular/login' => 'exams#login'
  # match 'vestibular/agendado' => 'exams#agendado'
  # match 'vestibular/enem' => 'enems#new'
  # match 'enem' => 'enems#new'
  # match 'enem' => 'exams#redirect_enem'
  # match 'vestibular/tradicional' => 'exams#redirect_tradicional'
  # match 'vestibular/informacoes' => 'exams#informacoes'
  # match 'vestibular/simulador' => 'exams#simulador'
  # match 'vestibular/editais' => 'exams#edital'
  # match 'vestibular-inverno' => 'redacaos#new'
  # match 'redacao' => 'redacaos#redacao'

end

app/models/award_gallery.rb
class AwardGallery < ActiveRecord::Base
  attr_accessible :name, :active, :published, :award_img, :award_id
  
  has_attached_file :award_img,
                      :styles =>{
                        :thumb=> "50x50#",
                        :big_thumb=>"100x100#",
                        :thumb_show => "135x104#"
                        } 
                        
  belongs_to :award
  
  
end

app/controllers/admin/award_galleries_controller.rb
class Admin::AwardGalleriesController < ApplicationController
  access_control do
      allow :administrator, :all
      allow :marketing, :all
  end
  
  layout "admin"
  before_filter :load_award
   
  
  def index
    @award_galleries = @award.award_galleries.all_active
  end

  def show
    @award_gallery = @award.award_galleries.find(params[:id])
  end

  def new
    @award_gallery = @award.award_galleries.build
  end

  def create
    @award_gallery = @award.award_galleries.build(params[:award_gallery])
    if @award_gallery.save
      redirect_to [:admin, @award, @award_gallery], :notice => "Successfully created award gallery."
    else
      render :action => 'new'
    end
  end

  def edit
    @award_gallery = @award.award_galleries.find(params[:id])
  end

  def update
    @award_gallery = @award.award_galleries.find(params[:id])
    if @award_gallery.update_attributes(params[:award_gallery])
      redirect_to [:admin, @award, @award_gallery], :notice  => "Successfully updated award gallery."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @award_gallery = @award.award_galleries.find(params[:id])
    @award_gallery.newdestroy
    redirect_to admin_award_award_galleries_url, :notice => "Successfully destroyed award gallery."
  end
  
  def load_award
    @award= Award.find_by_id(params[:award_id])
  end
end

app/helpers/admin/award_galleries_helper.rb
module Admin::AwardGalleriesHelper
end

app/views/admin/award_galleries/_form.html.haml
= form_for [:admin, @award, @award_gallery] do |f|
  -if f.error_messages
    .alert.alert-danger.alert-dismissable
      %i.fa.fa-ban
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %b Alert!
      Confira os campos marcados em vermelho.
  = f.error_messages
  .box-body    
    .form-group 
      = f.label :name, "Nome"
       
      = f.text_field :name, :class => "form-control"
    .form-group 
      = f.label :published, "Publicado"
       
      = f.check_box :published
    .form-group
      =f.label :award_img, "Imagem"
      
      =f.file_field :award_img, :class => "form-control"
      
    = f.submit "Salvar", :class =>"btn btn-primary"

app/views/admin/award_galleries/edit.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h1.m-0.text-dark Galeria de Imagens - #{@award.name}
      / /.col
      .col-sm-6
        %ol.breadcrumb.float-sm-right
          %li.breadcrumb-item
            %a{:href => admin_root_path} Home
          %li.breadcrumb-item.active Premiações
          %li.breadcrumb-item.active #{@award.name}
          %li.breadcrumb-item.active Galeria de Imagens
        / /.col
      / /.row
    / /.container-fluid
  / /.content-header
%section.content
  .col-xs-12
    .card.card-primary
      .card-header
        %h3.card-title
          Editar
          = @department.name
      .p-4

        = render 'form'
      .card-footer
        %p= link_to "Visualizar Todos", admin_award_award_galleries_path, :class => "btn btn-default"

app/views/admin/award_galleries/index.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h1.m-0.text-dark Galeria de Imagens - #{@award.name}
      / /.col
      .col-sm-6
        %ol.breadcrumb.float-sm-right
          %li.breadcrumb-item
            %a{:href => admin_root_path} Home
          %li.breadcrumb.active Premiações
          %li.breadcrumb.active #{@award.name}
          %li.breadcrumb.active Galeria de Imagens
        / /.col
      / /.row
    / /.container-fluid
  / /.content-header
%section.content
  .col-xs-12
    .card.card-primary.card-outline
      .card-header
        %h3.card-title
          Imagens
      .p-4
        %table.table.table-hover
          %tr
            %th Imagem
            %th Nome
            %th Publicado
            %th Ações
          - for award_gallery in @award_galleries
            %tr
              %td= image_tag(award_gallery.award_img.url(:thumb)) if award_gallery.award_img.file?
              %td= award_gallery.name
              %td= show_boolean(award_gallery.published)
              %td
                =link_to 'Visualizar', [:admin, @award, award_gallery], :class => "btn btn-default"
                =link_to 'Editar', edit_admin_award_award_gallery_path(@award, award_gallery), :class => "btn btn-default"
                =link_to 'Excluir', [:admin, @award, award_gallery], :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-default"
      .card-footer
        %p
          = link_to "Nova imagem", new_admin_award_award_gallery_path, :class => "btn btn-primary"
          = link_to "Retornar", admin_awards_path, :class => "btn btn-primary"

app/views/admin/award_galleries/new.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h1.m-0.text-dark Galeria de Imagens - #{@award.name}
      / /.col
      .col-sm-6
        %ol.breadcrumb.float-sm-right
          %li.breadcrumb-item
            %a{:href => admin_root_path} Home
          %li.breadcrumb-item.active Premiações
          %li.breadcrumb-item.active #{@award.name}
          %li.breadcrumb-item.active Galeria de Imagens
        / /.col
      / /.row
    / /.container-fluid
  / /.content-header
%section.content
  .col-xs-12
    .card.card-primary
      .card-header
        %h3.card-title Nova Imagem
      .p-4
        = render 'form'

      .card-footer
        %p= link_to "Back to List", admin_award_award_galleries_path, :class => "btn btn-default"

app/views/admin/award_galleries/show.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h1.m-0.text-dark Galeria de Imagens - #{@award.name}
      / /.col
      .col-sm-6
        %ol.breadcrumb.float-sm-right
          %li.breadcrumb-item
            %a{:href => admin_root_path} Home
          %li.breadcrumb-item.active Premiações
          %li.breadcrumb-item.active #{@award.name}
          %li.breadcrumb-item.active Galeria de Imagens
        / /.col
      / /.row
    / /.container-fluid
  / /.content-header
%section.content
  .col-xs-12
    .card.card-primary
      .card-header
        %h3.card-title Imagens
      .p-4
        %p
          %strong Nome:
          = @award_gallery.name
        %p
          %strong Publicado:
          = show_boolean(@award_gallery.published)
        %p
          %strong Imagem:
          =image_tag(@award_gallery.award_img.url) if @award_gallery.award_img.file?
      .card-footer
        %p
          = link_to "Editar", edit_admin_award_award_gallery_path(@award, @award_gallery), :class => "btn btn-default"
          = link_to "Visualizar Todas", admin_award_award_galleries_path, :class => "btn btn-default"
          = link_to "Excluir", [:admin, @award, @award_gallery], :confirm => 'Está certo disto?', :method => :delete, :class => "btn btn-default"